apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: componentversions.ocm.software
spec:
  group: ocm.software
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              component:
                type: string
              version:
                type: string
              repository:
                type: string
          status:
            type: object
  scope: Namespaced
  names:
    plural: componentversions
    singular: componentversion
    kind: ComponentVersion
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ocmconfigurations.ocm.software
spec:
  group: ocm.software
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              componentVersion:
                type: object
              configuration:
                type: object
          status:
            type: object
  scope: Namespaced
  names:
    plural: ocmconfigurations
    singular: ocmconfiguration
    kind: OCMConfiguration
