apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: default
data:
  app.properties: |
    app.name=MyApp
    app.version=v1.0.0
    database.url=postgresql://localhost:5432/myapp
    logging.level=INFO
