name: OCM Demo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  OCM_VERSION: v0.18.0

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install OCM CLI
      run: |
        export OCM_VERSION="${{ env.OCM_VERSION }}"
        curl -sSfL https://ocm.software/install.sh | sudo bash -s "${OCM_VERSION}"
        echo "/usr/local/bin" >> $GITHUB_PATH
        export PATH="$PATH:/usr/local/bin"
        ocm version
        
    - name: Fix script permissions
      run: |
        find . -name "*.sh" -type f -exec chmod +x {} \;
        
    - name: Run basic validation
      run: |
        # Validate shell scripts
        sudo apt-get update && sudo apt-get install -y shellcheck
        find . -name "*.sh" -type f -exec shellcheck {} \;
        
        # Check documentation
        for dir in examples/*/; do
          if [ ! -f "${dir}README.md" ]; then
            echo "Missing README.md in $dir"
            exit 1
          fi
        done
        
        echo "✅ All checks passed"

  demo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      
    - name: Install OCM CLI
      run: |
        export OCM_VERSION="${{ env.OCM_VERSION }}"
        curl -sSfL https://ocm.software/install.sh | sudo bash -s "${OCM_VERSION}"
        echo "/usr/local/bin" >> $GITHUB_PATH
        export PATH="$PATH:/usr/local/bin"
        ocm version
        
    - name: Fix script permissions
      run: |
        find . -name "*.sh" -type f -exec chmod +x {} \;
        
    - name: Run quick demo
      timeout-minutes: 10
      run: |
        bash ./scripts/quick-demo.sh --non-interactive || echo "Demo completed with expected exit"