name: OCM Demo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup environment
      run: |
        # Install OCM CLI
        echo "Installing latest OCM CLI..."
        curl -s https://ocm.software/install.sh | sudo bash
        echo "/usr/local/bin" >> $GITHUB_PATH
        export PATH="/usr/local/bin:$PATH"
        ocm version
        
        # Fix script permissions
        find . -name "*.sh" -type f -exec chmod +x {} \;
        
    - name: Run validation
      run: |
        # Install shellcheck
        sudo apt-get update && sudo apt-get install -y shellcheck
        
        # Validate shell scripts
        find . -name "*.sh" -type f -exec shellcheck {} \;
        
        # Check documentation structure
        for dir in examples/*/; do
          if [ ! -f "${dir}README.md" ]; then
            echo "Missing README.md in $dir"
            exit 1
          fi
        done
        
        echo "✅ All validation checks passed"

  demo:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      
    - name: Setup environment
      run: |
        # Install OCM CLI
        echo "Installing latest OCM CLI..."
        curl -s https://ocm.software/install.sh | sudo bash
        echo "/usr/local/bin" >> $GITHUB_PATH
        export PATH="/usr/local/bin:$PATH"
        ocm version
        
        # Fix script permissions
        find . -name "*.sh" -type f -exec chmod +x {} \;
        
    - name: Run demo
      timeout-minutes: 10
      run: |
        if ! bash ./scripts/quick-demo.sh --non-interactive; then
          echo "❌ Demo failed. Check logs above for details."
          exit 1
        fi